/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseResponse } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesDeleteCourseDeleteCourseResponse } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesEditCourseEditCourseResponse } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesListCourseListCourseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel } from '../models';
/**
 * CoursesApi - axios parameter creator
 * @export
 */
export const CoursesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest} [igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCourse: async (igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest?: IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/courses`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCourse: async (courseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('deleteCourse', 'courseId', courseId)
            const localVarPath = `/api/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} courseId 
         * @param {IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest} [igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editCourse: async (courseId: number, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest?: IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'courseId' is not null or undefined
            assertParamExists('editCourse', 'courseId', courseId)
            const localVarPath = `/api/courses/{courseId}`
                .replace(`{${"courseId"}}`, encodeURIComponent(String(courseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseById: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCourseById', 'id', id)
            const localVarPath = `/api/courses/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesListCourseListCourseRequest} [igescConectaAPIFeaturesCoursesListCourseListCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCourse: async (igescConectaAPIFeaturesCoursesListCourseListCourseRequest?: IgescConectaAPIFeaturesCoursesListCourseListCourseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/courses/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesCoursesListCourseListCourseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CoursesApi - functional programming interface
 * @export
 */
export const CoursesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CoursesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest} [igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest?: IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.createCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteCourse(courseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesCoursesDeleteCourseDeleteCourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteCourse(courseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.deleteCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} courseId 
         * @param {IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest} [igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async editCourse(courseId: number, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest?: IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesCoursesEditCourseEditCourseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.editCourse(courseId, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.editCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCourseById(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCourseById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.getCourseById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesListCourseListCourseRequest} [igescConectaAPIFeaturesCoursesListCourseListCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest?: IgescConectaAPIFeaturesCoursesListCourseListCourseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CoursesApi.listCourse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CoursesApi - factory interface
 * @export
 */
export const CoursesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CoursesApiFp(configuration)
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest} [igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest?: IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseResponse> {
            return localVarFp.createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} courseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteCourse(courseId: number, options?: any): AxiosPromise<IgescConectaAPIFeaturesCoursesDeleteCourseDeleteCourseResponse> {
            return localVarFp.deleteCourse(courseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} courseId 
         * @param {IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest} [igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        editCourse(courseId: number, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest?: IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesCoursesEditCourseEditCourseResponse> {
            return localVarFp.editCourse(courseId, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCourseById(id: number, options?: any): AxiosPromise<IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel> {
            return localVarFp.getCourseById(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesCoursesListCourseListCourseRequest} [igescConectaAPIFeaturesCoursesListCourseListCourseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest?: IgescConectaAPIFeaturesCoursesListCourseListCourseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel> {
            return localVarFp.listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CoursesApi - object-oriented interface
 * @export
 * @class CoursesApi
 * @extends {BaseAPI}
 */
export class CoursesApi extends BaseAPI {
    /**
     * 
     * @param {IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest} [igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest?: IgescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).createCourse(igescConectaAPIFeaturesCoursesCreateCourseCreateCourseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} courseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public deleteCourse(courseId: number, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).deleteCourse(courseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} courseId 
     * @param {IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest} [igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public editCourse(courseId: number, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest?: IgescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).editCourse(courseId, igescConectaAPIFeaturesCoursesEditCourseEditCourseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public getCourseById(id: number, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).getCourseById(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IgescConectaAPIFeaturesCoursesListCourseListCourseRequest} [igescConectaAPIFeaturesCoursesListCourseListCourseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CoursesApi
     */
    public listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest?: IgescConectaAPIFeaturesCoursesListCourseListCourseRequest, options?: RawAxiosRequestConfig) {
        return CoursesApiFp(this.configuration).listCourse(igescConectaAPIFeaturesCoursesListCourseListCourseRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

