/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * InativarEmpresaEndpointApi - axios parameter creator
 * @export
 */
export const InativarEmpresaEndpointApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} cnpj 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmpresasCnpjDelete: async (cnpj: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'cnpj' is not null or undefined
            assertParamExists('apiEmpresasCnpjDelete', 'cnpj', cnpj)
            const localVarPath = `/api/empresas/{cnpj}`
                .replace(`{${"cnpj"}}`, encodeURIComponent(String(cnpj)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InativarEmpresaEndpointApi - functional programming interface
 * @export
 */
export const InativarEmpresaEndpointApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InativarEmpresaEndpointApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} cnpj 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEmpresasCnpjDelete(cnpj: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiEmpresasCnpjDelete(cnpj, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InativarEmpresaEndpointApi.apiEmpresasCnpjDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InativarEmpresaEndpointApi - factory interface
 * @export
 */
export const InativarEmpresaEndpointApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InativarEmpresaEndpointApiFp(configuration)
    return {
        /**
         * 
         * @param {string} cnpj 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEmpresasCnpjDelete(cnpj: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiEmpresasCnpjDelete(cnpj, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InativarEmpresaEndpointApi - object-oriented interface
 * @export
 * @class InativarEmpresaEndpointApi
 * @extends {BaseAPI}
 */
export class InativarEmpresaEndpointApi extends BaseAPI {
    /**
     * 
     * @param {string} cnpj 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InativarEmpresaEndpointApi
     */
    public apiEmpresasCnpjDelete(cnpj: string, options?: RawAxiosRequestConfig) {
        return InativarEmpresaEndpointApiFp(this.configuration).apiEmpresasCnpjDelete(cnpj, options).then((request) => request(this.axios, this.basePath));
    }
}

