/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseResponse } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseViewModel } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdViewModel } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest } from '../models';
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseResponse } from '../models';
/**
 * OriginsBusinessCasesApi - axios parameter creator
 * @export
 */
export const OriginsBusinessCasesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOriginBusinessCase: async (igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/origins-business-cases/CreateOriginBusinessCase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOriginBusinessCase: async (originBusinessCaseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'originBusinessCaseId' is not null or undefined
            assertParamExists('deleteOriginBusinessCase', 'originBusinessCaseId', originBusinessCaseId)
            const localVarPath = `/api/origins-business-cases/{originBusinessCaseId}`
                .replace(`{${"originBusinessCaseId"}}`, encodeURIComponent(String(originBusinessCaseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOriginBusinessCase: async (originBusinessCaseId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'originBusinessCaseId' is not null or undefined
            assertParamExists('getOriginBusinessCase', 'originBusinessCaseId', originBusinessCaseId)
            const localVarPath = `/api/origins-business-cases/{originBusinessCaseId}`
                .replace(`{${"originBusinessCaseId"}}`, encodeURIComponent(String(originBusinessCaseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginBusinessCase: async (igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/origins-business-cases/ListOriginBusinessCase`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginsBusinessCaseByBusinessCaseId: async (igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/origins-business-cases/ListOriginsBusinessCaseByBusinessCaseId`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOriginBusinessCase: async (originBusinessCaseId: number, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'originBusinessCaseId' is not null or undefined
            assertParamExists('updateOriginBusinessCase', 'originBusinessCaseId', originBusinessCaseId)
            const localVarPath = `/api/origins-business-cases/{originBusinessCaseId}`
                .replace(`{${"originBusinessCaseId"}}`, encodeURIComponent(String(originBusinessCaseId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OriginsBusinessCasesApi - functional programming interface
 * @export
 */
export const OriginsBusinessCasesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OriginsBusinessCasesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.createOriginBusinessCase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOriginBusinessCase(originBusinessCaseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOriginBusinessCase(originBusinessCaseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.deleteOriginBusinessCase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOriginBusinessCase(originBusinessCaseId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOriginBusinessCase(originBusinessCaseId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.getOriginBusinessCase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.listOriginBusinessCase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdViewModel>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.listOriginsBusinessCaseByBusinessCaseId']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOriginBusinessCase(originBusinessCaseId: number, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOriginBusinessCase(originBusinessCaseId, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OriginsBusinessCasesApi.updateOriginBusinessCase']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OriginsBusinessCasesApi - factory interface
 * @export
 */
export const OriginsBusinessCasesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OriginsBusinessCasesApiFp(configuration)
    return {
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseResponse> {
            return localVarFp.createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOriginBusinessCase(originBusinessCaseId: number, options?: any): AxiosPromise<void> {
            return localVarFp.deleteOriginBusinessCase(originBusinessCaseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOriginBusinessCase(originBusinessCaseId: number, options?: any): AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse> {
            return localVarFp.getOriginBusinessCase(originBusinessCaseId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseViewModel> {
            return localVarFp.listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdViewModel> {
            return localVarFp.listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} originBusinessCaseId 
         * @param {IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOriginBusinessCase(originBusinessCaseId: number, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options?: any): AxiosPromise<IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseResponse> {
            return localVarFp.updateOriginBusinessCase(originBusinessCaseId, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OriginsBusinessCasesApi - object-oriented interface
 * @export
 * @class OriginsBusinessCasesApi
 * @extends {BaseAPI}
 */
export class OriginsBusinessCasesApi extends BaseAPI {
    /**
     * 
     * @param {IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).createOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesCreateOriginBusinessCaseCreateOriginBusinessCaseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} originBusinessCaseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public deleteOriginBusinessCase(originBusinessCaseId: number, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).deleteOriginBusinessCase(originBusinessCaseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} originBusinessCaseId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public getOriginBusinessCase(originBusinessCaseId: number, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).getOriginBusinessCase(originBusinessCaseId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).listOriginBusinessCase(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginBusinessCaseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest} [igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).listOriginsBusinessCaseByBusinessCaseId(igescConectaAPIFeaturesOriginsBusinessCasesListOriginsBusinessCasesListOriginsBusinessCaseByBusinessCaseIdRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} originBusinessCaseId 
     * @param {IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest} [igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OriginsBusinessCasesApi
     */
    public updateOriginBusinessCase(originBusinessCaseId: number, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest?: IgescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options?: RawAxiosRequestConfig) {
        return OriginsBusinessCasesApiFp(this.configuration).updateOriginBusinessCase(originBusinessCaseId, igescConectaAPIFeaturesOriginsBusinessCasesUpdateOriginBusinessCaseUpdateOriginBusinessCaseRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

