/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompanyViewModel
 */
export interface CompanyViewModel {
    /**
     * 
     * @type {number}
     * @memberof CompanyViewModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof CompanyViewModel
     */
    'cnpj'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyViewModel
     */
    'nome'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyViewModel
     */
    'razaoSocial'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyViewModel
     */
    'telefone'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CompanyViewModel
     */
    'ativa'?: boolean;
}

