/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateOscRequest
 */
export interface CreateOscRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'objective'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'corporateName'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOscRequest
     */
    'oscPrimaryDocumment'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOscRequest
     */
    'beneficiariesIds'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOscRequest
     */
    'originsBusinessCasesIds'?: Array<number>;
}

