/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateEmpresaCommand
 */
export interface CreateEmpresaCommand {
    /**
     * 
     * @type {string}
     * @memberof CreateEmpresaCommand
     */
    'cnpj'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmpresaCommand
     */
    'nome'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmpresaCommand
     */
    'endereco'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmpresaCommand
     */
    'telefone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEmpresaCommand
     */
    'email'?: string;
}

