/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreatePersonResponse
 */
export interface CreatePersonResponse {
    /**
     * 
     * @type {number}
     * @memberof CreatePersonResponse
     */
    'personId'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'personalDocumment'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'secondaryEmail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'primaryPhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'secondaryPhone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'education1'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'education2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreatePersonResponse
     */
    'professionalActivity'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CreatePersonResponse
     */
    'isActive'?: boolean;
}

