/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOscBeneficiaryResponse } from './get-osc-beneficiary-response';
// May contain unused imports in some cases
// @ts-ignore
import type { GetOscOriginBusinessCaseResponse } from './get-osc-origin-business-case-response';

/**
 * 
 * @export
 * @interface GetOscResponse
 */
export interface GetOscResponse {
    /**
     * 
     * @type {number}
     * @memberof GetOscResponse
     */
    'oscId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'corporateName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'objective'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'neighborhood'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'webUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'socialMedia'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOscResponse
     */
    'oscPrimaryDocumment'?: string | null;
    /**
     * 
     * @type {Array<GetOscBeneficiaryResponse>}
     * @memberof GetOscResponse
     */
    'beneficiaries'?: Array<GetOscBeneficiaryResponse>;
    /**
     * 
     * @type {Array<GetOscOriginBusinessCaseResponse>}
     * @memberof GetOscResponse
     */
    'originsBusinessCases'?: Array<GetOscOriginBusinessCaseResponse>;
}

