/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TeamViewModel } from './team-view-model';

/**
 * 
 * @export
 * @interface GetCourseByIdViewModel
 */
export interface GetCourseByIdViewModel {
    /**
     * 
     * @type {number}
     * @memberof GetCourseByIdViewModel
     */
    'courseId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCourseByIdViewModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof GetCourseByIdViewModel
     */
    'isDeleted'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GetCourseByIdViewModel
     */
    'teamsCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GetCourseByIdViewModel
     */
    'createdBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCourseByIdViewModel
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof GetCourseByIdViewModel
     */
    'updatedBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetCourseByIdViewModel
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<TeamViewModel>}
     * @memberof GetCourseByIdViewModel
     */
    'teams'?: Array<TeamViewModel>;
}

