/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetBeneficiaryOscResponse } from './get-beneficiary-osc-response';

/**
 * 
 * @export
 * @interface GetBeneficiaryResponse
 */
export interface GetBeneficiaryResponse {
    /**
     * 
     * @type {number}
     * @memberof GetBeneficiaryResponse
     */
    'beneficiaryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetBeneficiaryResponse
     */
    'name'?: string;
    /**
     * 
     * @type {Array<GetBeneficiaryOscResponse>}
     * @memberof GetBeneficiaryResponse
     */
    'oscs'?: Array<GetBeneficiaryOscResponse>;
}

