/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetOriginBusinessCaseOscResponse } from './get-origin-business-case-osc-response';

/**
 * 
 * @export
 * @interface GetOriginBusinessCaseResponse
 */
export interface GetOriginBusinessCaseResponse {
    /**
     * 
     * @type {number}
     * @memberof GetOriginBusinessCaseResponse
     */
    'originBusinessCaseId'?: number;
    /**
     * 
     * @type {string}
     * @memberof GetOriginBusinessCaseResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof GetOriginBusinessCaseResponse
     */
    'notes'?: string;
    /**
     * 
     * @type {Array<GetOriginBusinessCaseOscResponse>}
     * @memberof GetOriginBusinessCaseResponse
     */
    'oscs'?: Array<GetOriginBusinessCaseOscResponse> | null;
}

