/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesListCourseCourseViewModel } from './igesc-conecta-apifeatures-courses-list-course-course-view-model';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel
 */
export interface IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel
     */
    'totalItems'?: number;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesCoursesListCourseCourseViewModel>}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseListCourseViewModel
     */
    'items'?: Array<IgescConectaAPIFeaturesCoursesListCourseCourseViewModel>;
}

