/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseOscResponse } from './igesc-conecta-apifeatures-origins-business-cases-get-origin-business-case-get-origin-business-case-osc-response';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse
 */
export interface IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse
     */
    'originBusinessCaseId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse
     */
    'notes'?: string;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseOscResponse>}
     * @memberof IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseResponse
     */
    'oscs'?: Array<IgescConectaAPIFeaturesOriginsBusinessCasesGetOriginBusinessCaseGetOriginBusinessCaseOscResponse> | null;
}

