/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryOscResponse } from './igesc-conecta-apifeatures-beneficiares-get-beneficiary-get-beneficiary-endpoint-get-beneficiary-osc-response';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse
 */
export interface IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse
     */
    'beneficiaryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse
     */
    'notes'?: string;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryOscResponse>}
     * @memberof IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryResponse
     */
    'oscs'?: Array<IgescConectaAPIFeaturesBeneficiaresGetBeneficiaryGetBeneficiaryEndpointGetBeneficiaryOscResponse>;
}

