/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesOscsUpdateOscUpdateBeneficiaryInOscResponse } from './igesc-conecta-apifeatures-oscs-update-osc-update-beneficiary-in-osc-response';
// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesOscsUpdateOscUpdateOriginBusinessCaseInOscResponse } from './igesc-conecta-apifeatures-oscs-update-osc-update-origin-business-case-in-osc-response';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
 */
export interface IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'oscId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'corporateName'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'objective'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'zipCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'oscPrimaryDocumment'?: string | null;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesOscsUpdateOscUpdateBeneficiaryInOscResponse>}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'beneficiaries'?: Array<IgescConectaAPIFeaturesOscsUpdateOscUpdateBeneficiaryInOscResponse> | null;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesOscsUpdateOscUpdateOriginBusinessCaseInOscResponse>}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscResponse
     */
    'originsBusinessCases'?: Array<IgescConectaAPIFeaturesOscsUpdateOscUpdateOriginBusinessCaseInOscResponse> | null;
}

