/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
 */
export interface IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'valor'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'data'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'doadorPessoaCPF'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'doadorEmpresaCNPJ'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'destinoTipo'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'destinoTurmaId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesDonationsCreateDonationCreateDonationCommand
     */
    'destinoOSCCodigo'?: string | null;
}

