/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
 */
export interface IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesUsersUpdateUserUpdateUserRequest
     */
    'role'?: string | null;
}

