/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Filter } from './filter';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesPersonsListPersonListPersonRequest
 */
export interface IgescConectaAPIFeaturesPersonsListPersonListPersonRequest {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesPersonsListPersonListPersonRequest
     */
    'pageNumber'?: number;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesPersonsListPersonListPersonRequest
     */
    'pageSize'?: number;
    /**
     * 
     * @type {Array<Filter>}
     * @memberof IgescConectaAPIFeaturesPersonsListPersonListPersonRequest
     */
    'filters'?: Array<Filter>;
}

