/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
 */
export interface IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest {
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'corporateName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'objective'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'oscPrimaryDocumment'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'beneficiaryIds'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IgescConectaAPIFeaturesOscsUpdateOscUpdateOscRequest
     */
    'originBusinessCaseIds'?: Array<number> | null;
}

