/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesBeneficiaresListBeneficiariesBeneficiaryViewModel } from './igesc-conecta-apifeatures-beneficiares-list-beneficiaries-beneficiary-view-model';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesBeneficiaresListBeneficiariesListBeneficiaryViewModel
 */
export interface IgescConectaAPIFeaturesBeneficiaresListBeneficiariesListBeneficiaryViewModel {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesBeneficiaresListBeneficiariesListBeneficiaryViewModel
     */
    'totalItems'?: number;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesBeneficiaresListBeneficiariesBeneficiaryViewModel>}
     * @memberof IgescConectaAPIFeaturesBeneficiaresListBeneficiariesListBeneficiaryViewModel
     */
    'items'?: Array<IgescConectaAPIFeaturesBeneficiaresListBeneficiariesBeneficiaryViewModel>;
}

