/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesBusinessCasesUpdateBusinessCaseUpdateBusinessCaseRequest
 */
export interface IgescConectaAPIFeaturesBusinessCasesUpdateBusinessCaseUpdateBusinessCaseRequest {
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesBusinessCasesUpdateBusinessCaseUpdateBusinessCaseRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IgescConectaAPIFeaturesBusinessCasesUpdateBusinessCaseUpdateBusinessCaseRequest
     */
    'originsBusinessCasesIds'?: Array<number>;
}

