/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesUsersListUserUserViewModel } from './igesc-conecta-apifeatures-users-list-user-user-view-model';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesUsersListUserListUserViewModel
 */
export interface IgescConectaAPIFeaturesUsersListUserListUserViewModel {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesUsersListUserListUserViewModel
     */
    'totalItems'?: number;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesUsersListUserUserViewModel>}
     * @memberof IgescConectaAPIFeaturesUsersListUserListUserViewModel
     */
    'items'?: Array<IgescConectaAPIFeaturesUsersListUserUserViewModel>;
}

