/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IgescConectaAPIFeaturesCoursesListCourseTeamViewModel } from './igesc-conecta-apifeatures-courses-list-course-team-view-model';

/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
 */
export interface IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'courseId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'isDeleted'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'teamsCount'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'createdBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'createdAt'?: string;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'updatedBy'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Array<IgescConectaAPIFeaturesCoursesListCourseTeamViewModel>}
     * @memberof IgescConectaAPIFeaturesCoursesListCourseGetCourseByIdViewModel
     */
    'teams'?: Array<IgescConectaAPIFeaturesCoursesListCourseTeamViewModel>;
}

