/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesAuthResetPasswordResetPasswordRequest
 */
export interface IgescConectaAPIFeaturesAuthResetPasswordResetPasswordRequest {
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesAuthResetPasswordResetPasswordRequest
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesAuthResetPasswordResetPasswordRequest
     */
    'token'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesAuthResetPasswordResetPasswordRequest
     */
    'newPassword'?: string;
}

