/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
 */
export interface IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest {
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'lessonTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'finish'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'personTeamsIds'?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'projectProgramId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof IgescConectaAPIFeaturesTeamsCreateTeamCreateTeamRequest
     */
    'courseId'?: number;
}

