/* tslint:disable */
/* eslint-disable */
/**
 * IGESC API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
 */
export interface IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand {
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
     */
    'cnpj'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
     */
    'nome'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
     */
    'endereco'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
     */
    'telefone'?: string;
    /**
     * 
     * @type {string}
     * @memberof IgescConectaAPIFeaturesEmpresasCreateEmpresaCreateEmpresaCommand
     */
    'email'?: string;
}

