/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ListTeamItemViewModel
 */
export interface ListTeamItemViewModel {
    /**
     * 
     * @type {number}
     * @memberof ListTeamItemViewModel
     */
    'teamId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'lessonTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'finish'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListTeamItemViewModel
     */
    'projectProgramId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'projectProgramName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListTeamItemViewModel
     */
    'courseId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ListTeamItemViewModel
     */
    'courseName'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ListTeamItemViewModel
     */
    'personTeamsCount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListTeamItemViewModel
     */
    'isDeleted'?: boolean;
}

