/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OriginBusinessCaseByBusinessCaseIdViewModel } from './origin-business-case-by-business-case-id-view-model';

/**
 * 
 * @export
 * @interface ListOriginsBusinessCaseByBusinessCaseIdViewModel
 */
export interface ListOriginsBusinessCaseByBusinessCaseIdViewModel {
    /**
     * 
     * @type {number}
     * @memberof ListOriginsBusinessCaseByBusinessCaseIdViewModel
     */
    'totalItems'?: number;
    /**
     * 
     * @type {Array<OriginBusinessCaseByBusinessCaseIdViewModel>}
     * @memberof ListOriginsBusinessCaseByBusinessCaseIdViewModel
     */
    'items'?: Array<OriginBusinessCaseByBusinessCaseIdViewModel>;
}

