/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TeamViewModel
 */
export interface TeamViewModel {
    /**
     * 
     * @type {number}
     * @memberof TeamViewModel
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof TeamViewModel
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamViewModel
     */
    'lessonTime'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamViewModel
     */
    'start'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TeamViewModel
     */
    'finish'?: string | null;
}

