/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateOscRequest
 */
export interface UpdateOscRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'corporateName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'objective'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'neighborhood'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'state'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'webUrl'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'socialMedia'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateOscRequest
     */
    'oscPrimaryDocumment'?: string | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateOscRequest
     */
    'beneficiaryIds'?: Array<number> | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof UpdateOscRequest
     */
    'originBusinessCaseIds'?: Array<number> | null;
}

