/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateCompanyCommand
 */
export interface UpdateCompanyCommand {
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'cnpj'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'companyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'corporateReason'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'fieldOfActivity'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'zipCode'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'address'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'neighborhood'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'city'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'state'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'website'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCompanyCommand
     */
    'socialMedia'?: string | null;
}

