/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateDonationCommand
 */
export interface UpdateDonationCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateDonationCommand
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateDonationCommand
     */
    'value'?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateDonationCommand
     */
    'donationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateDonationCommand
     */
    'oscId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateDonationCommand
     */
    'courseId'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateDonationCommand
     */
    'teamId'?: number | null;
}

