/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserViewModel
 */
export interface UserViewModel {
    /**
     * 
     * @type {number}
     * @memberof UserViewModel
     */
    'userId'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserViewModel
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserViewModel
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserViewModel
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserViewModel
     */
    'phoneNumber'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserViewModel
     */
    'isActive'?: boolean;
}

