/* tslint:disable */
/* eslint-disable */
/**
 * IgescConecta.API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export * from './apis/auth-api';
export * from './apis/beneficiaries-api';
export * from './apis/business-cases-api';
export * from './apis/courses-api';
export * from './apis/create-donation-endpoint-api';
export * from './apis/create-empresa-endpoint-api';
export * from './apis/delete-donation-endpoint-api';
export * from './apis/inativar-empresa-endpoint-api';
export * from './apis/list-donation-endpoint-api';
export * from './apis/list-empresa-endpoint-api';
export * from './apis/origins-business-cases-api';
export * from './apis/oscs-api';
export * from './apis/teams-api';
export * from './apis/update-empresa-endpoint-api';
export * from './apis/uptade-donation-endpoint-api';
export * from './apis/users-api';

